export type Product = {
  id: string
  name: string
  category: string
  collection: string
  price: number
  compareAtPrice?: number
  image: string
  alt: string
  description: string
  material: string
  diamondDetails: string
  tag: string
  sizes?: string[]
  featured?: boolean
  bestseller?: boolean
  newArrival?: boolean
}

export const categories = [
  { name: 'Rings', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80', alt: 'Diamond ring from Shree Yash Diamond and Jewels' },
  { name: 'Bracelets', image: '/bracelet1.avif', alt: 'Fine bracelet design from Shree Yash Diamond and Jewels' },
  { name: 'Pendants', image: '/pendant1.jpg', alt: 'Diamond pendant by Shree Yash Diamond and Jewels' },
  { name: 'Chains', image: '/chains.webp', alt: 'Modern necklace chain from Shree Yash Diamond and Jewels' },
  { name: 'Earrings', image: '/sbc earring.png', alt: 'Elegant diamond earrings from Shree Yash Diamond and Jewels' },
  { name: 'Necklaces', image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=80', alt: 'Luxury necklace from Shree Yash Diamond and Jewels' },
  { name: 'Anklets', image: '/anklet.webp', alt: 'Fine anklet design by Shree Yash Diamond and Jewels' },
  { name: 'Bangles', image: '/sbc bangles.jpg', alt: 'Elegant bangle design from Shree Yash Diamond and Jewels' },
  { name: 'Bridal Earring', image: '/bride earring.jpg', alt: 'Bridal earring styling by Shree Yash Diamond and Jewels' },
  { name: 'Bridal Bangles', image: '/bride bangle.webp', alt: 'Bridal bangles styling by Shree Yash Diamond and Jewels' },
  { name: 'Bridal Necklace', image: '/bride.jpeg', alt: 'Bridal necklace styling by Shree Yash Diamond and Jewels' },
  { name: 'Bridal Other Jewelleries', image: '/sbc other jewels.jpg', alt: 'Bridal jewellery styling by Shree Yash Diamond and Jewels' },
]

const existingProducts: Product[] = [
  {
    id: 'celeste-diamond-ring',
    name: 'Celeste Diamond Ring',
    category: 'Rings',
    collection: 'Modern Romance',
    price: 28900,
    compareAtPrice: 32900,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80',
    alt: 'Celeste Diamond Ring by Shree Yash Diamond and Jewels',
    description: 'A graceful diamond ring designed for modern heirlooms and everyday celebrations.',
    material: '18K gold vermeil',
    diamondDetails: 'Round brilliant solitaire with soft sparkle finish',
    tag: 'engagement',
    sizes: ['5', '6', '7', '8'],
    featured: true,
    newArrival: true,

  },
  {
    id: 'noor-solitaire-ring',
    name: 'Noor Solitaire Ring',
    category: 'Rings',
    collection: 'Monarch',
    price: 34900,
    compareAtPrice: 39900,
    image: '/nsr.webp',
    alt: 'Noor Solitaire Ring by Shree Yash Diamond and Jewels',
    description: 'A solitaire ring with a sculpted band and a softly brilliant centre stone.',
    material: '18K gold vermeil',
    diamondDetails: 'Single stone diamond setting with refined edges',
    tag: 'solitaire',
    sizes: ['5', '6', '7', '8', '9'],
    bestseller: true,
    newArrival: true,

  },
  {
    id: 'aarna-diamond-pendant',
    name: 'Aarna Diamond Pendant',
    category: 'Pendants',
    collection: 'Dusk Aura',
    price: 22900,
    compareAtPrice: 26900,
    image: '/pendant1.jpg',
    alt: 'Aarna Diamond Pendant by Shree Yash Diamond and Jewels',
    description: 'An elegant pendant balancing softness and shine for daily wear and gifting.',
    material: '18K gold vermeil',
    diamondDetails: 'Accented with brilliant-cut stones',
    tag: 'pendant',
    sizes: ['16 inch', '18 inch', '20 inch'],
    featured: true,

  },
  {
    id: 'vesha-diamond-pendant',
    name: 'Vesha Diamond Pendant',
    category: 'Pendants',
    collection: 'Pearl Bloom',
    price: 25400,
    compareAtPrice: 29900,
    image: '/Vesha Diamond Pendant.avif',
    alt: 'Vesha Diamond Pendant by Shree Yash Diamond and Jewels',
    description: 'A luxe pendant with luminous accents created for festive gifting and everyday elegance.',
    material: 'Gold vermeil with brilliant stones',
    diamondDetails: 'Contemporary silhouette with light-catching accents',
    tag: 'pendant',
    sizes: ['16 inch', '18 inch'],

  },
  {
    id: 'meher-pearl-drop-earrings',
    name: 'Meher Pearl Drop Earrings',
    category: 'Earrings',
    collection: 'Pearl Bloom',
    price: 18900,
    compareAtPrice: 21900,
    image: '/mpd.webp',
    alt: 'Meher Pearl Drop Earrings by Shree Yash Diamond and Jewels',
    description: 'Pearl-drop earrings that add luminous grace to festive and evening looks.',
    material: 'Gold vermeil with cultured pearls',
    diamondDetails: 'Finely set accent stones',
    tag: 'pearl',
    bestseller: true,
    newArrival: true,

  },
  {
    id: 'naina-crescent-earrings',
    name: 'Naina Crescent Earrings',
    category: 'Earrings',
    collection: 'Moonlit Notes',
    price: 21400,
    compareAtPrice: 24400,
    image: '/nce.webp',
    alt: 'Naina Crescent Earrings by Shree Yash Diamond and Jewels',
    description: 'Modern crescent silhouettes with a delicate shimmer designed for elevated styling.',
    material: 'Gold vermeil and diamonds',
    diamondDetails: 'Light-catching accent stones',
    tag: 'crescent',
    bestseller: true,

  },
  {
    id: 'ira-halo-necklace',
    name: 'Ira Halo Necklace',
    category: 'Necklaces',
    collection: 'Halo Edit',
    price: 38900,
    compareAtPrice: 44900,
    image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=80',
    alt: 'Ira Halo Necklace by Shree Yash Diamond and Jewels',
    description: 'A luminous halo necklace designed for statement moments and layered styling.',
    material: 'Gold vermeil',
    diamondDetails: 'Halo-set stones providing a radiant profile',
    tag: 'necklace',
    sizes: ['16 inch', '18 inch', '20 inch'],
    bestseller: true,

  },
  {
    id: 'sahana-garden-necklace',
    name: 'Sahana Garden Necklace',
    category: 'Necklaces',
    collection: 'Bloom Edit',
    price: 42000,
    compareAtPrice: 48200,
    image: '/Sahana Garden Necklace.jpg',
    alt: 'Sahana Garden Necklace by Shree Yash Diamond and Jewels',
    description: 'An intricate necklace statement with layered floral sparkle for milestone evenings.',
    material: '18K gold vermeil',
    diamondDetails: 'Layered floral stone work and polished finish',
    tag: 'necklace',
    sizes: ['16 inch', '18 inch'],

  },
  {
    id: 'zoya-diamond-bracelet',
    name: 'Zoya Diamond Bracelet',
    category: 'Bracelets',
    collection: 'Everyday Luxe',
    price: 26900,
    compareAtPrice: 31900,
    image: '/bracelet1.avif',
    alt: 'Zoya Diamond Bracelet by Shree Yash Diamond and Jewels',
    description: 'Sculpted elegance for the wrist, ideal for everyday shine and occasion styling.',
    material: '18K gold vermeil',
    diamondDetails: 'Precision-set stones along a refined arc',
    tag: 'bracelet',
    sizes: ['6.5 inch', '7 inch', '7.5 inch'],
    featured: true,
    newArrival: true,

  },
  {
    id: 'navya-bangle-set',
    name: 'Navya Bangle Set',
    category: 'Bangles',
    collection: 'Festive Light',
    price: 31000,
    compareAtPrice: 35900,
    image: '/bb.webp',
    alt: 'Navya Bangle Set by Shree Yash Diamond and Jewels',
    description: 'A polished bangle set with luminous silhouettes built for statements and gifting.',
    material: 'Gold vermeil and diamonds',
    diamondDetails: 'Smooth engraved profile with diamond accents',
    tag: 'bangle',
    sizes: ['Medium', 'Large'],

  },
  {
    id: 'tara-anklet',
    name: 'Tara Anklet',
    category: 'Anklets',
    collection: 'Footnotes',
    price: 18200,
    compareAtPrice: 21400,
    image: '/anklet.webp',
    alt: 'Tara Anklet by Shree Yash Diamond and Jewels',
    description: 'A delicate anklet designed to add a subtle shimmer to festive looks and evening occasions.',
    material: 'Gold vermeil with accents',
    diamondDetails: 'Fine stone detailing and soft curvature',
    tag: 'anklet',
    sizes: ['Adjustable'],

  },
  {
    id: 'mira-chain',
    name: 'Mira Chain',
    category: 'Chains',
    collection: 'Minimal Glow',
    price: 21400,
    compareAtPrice: 24900,
    image: '/chains.webp',
    alt: 'Mira Chain by Shree Yash Diamond and Jewels',
    description: 'A refined chain with a minimal frame designed for layering and everyday luxury.',
    material: 'Gold vermeil',
    diamondDetails: 'Clean line detailing with polished finish',
    tag: 'chain',
    sizes: ['16 inch', '18 inch', '20 inch'],

  },
  {
    id: 'saanvi-bridal-set',
    name: 'Saanvi Bridal Set',
    category: 'Bridal Necklace',
    collection: 'Forever Moments',
    price: 54000,
    compareAtPrice: 62400,
    image: '/Saanvi Bridal Set.jpg',
    alt: 'Saanvi Bridal Set by Shree Yash Diamond and Jewels',
    description: 'A richly detailed bridal set balancing traditional artistry with refined sophistication.',
    material: 'Gold vermeil and diamonds',
    diamondDetails: 'Elevated bridal stone work with heirloom finish',
    tag: 'bridal',
    sizes: ['Custom sizing'],
    featured: true,

  },
]

const categoryProductCatalog: Record<string, Array<{
  name: string
  collection: string
  price: number
  compareAtPrice?: number
  image: string
  alt: string
  description: string
  material: string
  diamondDetails: string
  tag: string
  sizes?: string[]
  featured?: boolean
  bestseller?: boolean
  newArrival?: boolean
}>> = {
  Rings: [
    {
      name: 'Gold Solitaire Ring',
      collection: 'Lustre Signature',
      price: 24500,
      compareAtPrice: 28900,
      image: '/rs 1.jpg',
      alt: 'Gold solitaire ring by Shree Yash Diamond and Jewels',
      description: 'A classic solitaire ring with a luminous centre stone for everyday elegance and milestone gifting.',
      material: '18K gold vermeil',
      diamondDetails: 'Round brilliant centre stone with polished band',
      tag: 'solitaire',
      sizes: ['5', '6', '7', '8'],
      featured: true,
      bestseller: true,
      newArrival: true,
    },
    {
      name: 'Diamond Halo Ring',
      collection: 'Moonlit Glow',
      price: 32900,
      compareAtPrice: 37900,
      image: '/rs 2.jpg',
      alt: 'Diamond halo ring by Shree Yash Diamond and Jewels',
      description: 'A halo-set diamond ring crafted for refined bridal styling and celebratory gifting.',
      material: 'Gold vermeil with diamond accents',
      diamondDetails: 'Halo setting with brilliant-cut diamonds',
      tag: 'diamond',
      sizes: ['6', '7', '8', '9'],
      bestseller: true,
    },
    {
      name: 'Couple Ring Set',
      collection: 'Together Forever',
      price: 41800,
      compareAtPrice: 48900,
      image: '/rs 3.jpg',
      alt: 'Matching couple ring set by Shree Yash Diamond and Jewels',
      description: 'A matching pair of contemporary rings designed for couples and promise moments.',
      material: '18K gold vermeil',
      diamondDetails: 'Sculpted profiles with subtle sparkle accord',
      tag: 'couple',
      sizes: ['5', '6', '7', '8'],
      newArrival: true,
    },
  ],
  Bracelets: [
    {
      name: 'Gold Tennis Bracelet',
      collection: 'Soft Shine',
      price: 28600,
      compareAtPrice: 32900,
      image: '/Gold Tennis Bracelet.webp',
      alt: 'Gold tennis bracelet by Shree Yash Diamond and Jewels',
      description: 'An elegant tennis bracelet with graceful sparkle, designed for refined everyday wear.',
      material: 'Gold vermeil with diamonds',
      diamondDetails: 'Seamless diamond line with polished finish',
      tag: 'tennis',
      sizes: ['6.5 inch', '7 inch', '7.5 inch'],
      featured: true,
    },
    {
      name: 'Charm Bracelet',
      collection: 'Everyday Notes',
      price: 19800,
      compareAtPrice: 23900,
      image: '/charm.jpg',
      alt: 'Gold charm bracelet by Shree Yash Diamond and Jewels',
      description: 'A delicate charm bracelet that feels personal and effortless for everyday styling.',
      material: '18K gold vermeil',
      diamondDetails: 'Fine charm detailing and smooth clasp',
      tag: 'charms',
      sizes: ['6 inch', '7 inch'],
    },
    {
      name: 'Cuff Bracelet',
      collection: 'Statement Line',
      price: 25400,
      compareAtPrice: 29400,
      image: '/Cuff Bracelet.webp',
      alt: 'Gold cuff bracelet by Shree Yash Diamond and Jewels',
      description: 'A polished cuff bracelet with a broad silhouette ideal for layered festive styling.',
      material: 'Gold vermeil',
      diamondDetails: 'Smooth finish with subtle engraved detailing',
      tag: 'cuff',
      sizes: ['Medium', 'Large'],
      bestseller: true,
    },
  ],
  Pendants: [
    {
      name: 'Pearl Drop Pendant',
      collection: 'Pearl Bloom',
      price: 21600,
      compareAtPrice: 24800,
      image: '/Pearl Drop Pendant.webp',
      alt: 'Pearl drop pendant by Shree Yash Diamond and Jewels',
      description: 'A luminous pearl pendant bringing softness and depth to elegant occasion wear.',
      material: 'Gold vermeil with cultured pearls',
      diamondDetails: 'Pearl drop with minimal gemstone accents',
      tag: 'pearl',
      sizes: ['16 inch', '18 inch', '20 inch'],
      newArrival: true,
    },
    {
      name: 'Diamond Heart Pendant',
      collection: 'Love Notes',
      price: 23800,
      compareAtPrice: 27800,
      image: '/Diamond Heart Pendant.jpg',
      alt: 'Diamond heart pendant by Shree Yash Diamond and Jewels',
      description: 'A romantic heart pendant with scintillating diamond detailing for meaningful gifting.',
      material: 'Gold vermeil with diamonds',
      diamondDetails: 'Heart motif with brilliant-cut diamond finish',
      tag: 'heart',
      sizes: ['16 inch', '18 inch'],
      featured: true,
    },
    {
      name: 'Floral Pendant',
      collection: 'Petal Grace',
      price: 20200,
      compareAtPrice: 23900,
      image: '/Floral Pendant.jpg',
      alt: 'Floral pendant by Shree Yash Diamond and Jewels',
      description: 'A floral pendant balancing a delicate silhouette with a statement finish for festive evenings.',
      material: 'Gold vermeil with floral diamond setting',
      diamondDetails: 'Petal-inspired setting with airy sparkle',
      tag: 'floral',
      sizes: ['16 inch', '18 inch'],
    },
  ],
  Earrings: [
    {
      name: 'Gold Hoop Earrings',
      collection: 'Daily Luxe',
      price: 17200,
      compareAtPrice: 20500,
      image: '/Gold Hoop Earrings.jpeg',
      alt: 'Gold hoop earrings by Shree Yash Diamond and Jewels',
      description: 'Minimal gold hoops that instantly elevate everyday styling with a luxe, polished finish.',
      material: '18K gold vermeil',
      diamondDetails: 'Classic loop silhouette with subtle shimmer',
      tag: 'hoops',
      sizes: ['Medium', 'Large'],
      bestseller: true,
    },
    {
      name: 'Pearl Drop Earrings',
      collection: 'Pearl Illumination',
      price: 18900,
      compareAtPrice: 21900,
      image: '/Pearl Drop Earrings.jpg',
      alt: 'Pearl drop earrings by Shree Yash Diamond and Jewels',
      description: 'Sophisticated pearl drops designed for weddings, festive dinners, and statement evenings.',
      material: 'Gold vermeil with cultured pearls',
      diamondDetails: 'Delicate drop silhouette with polished sparkle',
      tag: 'pearl',
      sizes: ['One size'],
      featured: true,
    },
    {
      name: 'Jhumka Earrings',
      collection: 'Festive Drape',
      price: 22400,
      compareAtPrice: 26400,
      image: '/Jhumka Earrings.jpg',
      alt: 'Traditional jhumka earrings by Shree Yash Diamond and Jewels',
      description: 'Traditional jhumka styling with contemporary sparkle for vibrant occasion looks.',
      material: 'Gold vermeil with diamond accents',
      diamondDetails: 'Traditional jhumka craftsmanship with mirror polish',
      tag: 'jhumka',
      sizes: ['One size'],
      newArrival: true,
    },
  ],
  Necklaces: [
    {
      name: 'Pearl Layer Necklace',
      collection: 'Ocean Glow',
      price: 28100,
      compareAtPrice: 32900,
      image: '/Pearl Layer Necklace.jpeg',
      alt: 'Pearl layer necklace by Shree Yash Diamond and Jewels',
      description: 'A layered pearl necklace with a graceful silhouette suited for modern festive styling.',
      material: 'Gold vermeil with pearls',
      diamondDetails: 'Layered pearl cords with refined finish',
      tag: 'pearls',
      sizes: ['16 inch', '18 inch', '20 inch'],
      bestseller: true,
    },
    {
      name: 'Emerald Charm Necklace',
      collection: 'Forest Luxe',
      price: 31200,
      compareAtPrice: 36900,
      image: '/Emerald Charm Necklace.webp',
      alt: 'Emerald charm necklace by Shree Yash Diamond and Jewels',
      description: 'An emerald-inspired statement necklace tailored for evening glamour and curated gifting.',
      material: 'Gold vermeil with emerald-toned stones',
      diamondDetails: 'Statement profile with faceted accent stones',
      tag: 'emerald',
      sizes: ['18 inch', '20 inch'],
    },
    {
      name: 'Minimal Chain Necklace',
      collection: 'Everyday Edit',
      price: 16300,
      compareAtPrice: 19200,
      image: '/Minimal Chain Necklace.avif',
      alt: 'Minimal chain necklace by Shree Yash Diamond and Jewels',
      description: 'A sleek minimal chain that pairs easily with both festive and everyday silhouettes.',
      material: 'Gold vermeil',
      diamondDetails: 'Clean chain profile with soft polish',
      tag: 'minimal',
      sizes: ['16 inch', '18 inch'],
      newArrival: true,
    },
  ],
  Bangles: [
    {
      name: 'Rose Gold Bangle Set',
      collection: 'Blush Glow',
      price: 27500,
      compareAtPrice: 31900,
      image: '/Rose Gold Bangle Set.jpg',
      alt: 'Rose gold bangle set by Shree Yash Diamond and Jewels',
      description: 'A softly tinted bangle set with polished edges for graceful, layered styling.',
      material: 'Rose gold vermeil',
      diamondDetails: 'Polished filigree with subtle sparkle accents',
      tag: 'rose-gold',
      sizes: ['Medium', 'Large'],
      featured: true,
    },
    {
      name: 'Wedding Bangle Stack',
      collection: 'Forever Wedding',
      price: 34900,
      compareAtPrice: 39900,
      image: '/Wedding Bangle Stack.jpg',
      alt: 'Wedding bangle stack by Shree Yash Diamond and Jewels',
      description: 'A statement bridal bangle stack designed to elevate traditional wedding styling.',
      material: 'Gold vermeil with diamond detailing',
      diamondDetails: 'Stackable set with heirloom silhouette',
      tag: 'bridal',
      sizes: ['Medium', 'Large'],
      bestseller: true,
    },
    {
      name: 'Polished Daily Bangle',
      collection: 'Everyday Charm',
      price: 18400,
      compareAtPrice: 21900,
      image: '/Polished Daily Bangle.jpg',
      alt: 'Polished daily bangle by Shree Yash Diamond and Jewels',
      description: 'A refined bangle designed for daily sparkle and gifting moments that feel personal.',
      material: 'Gold vermeil',
      diamondDetails: 'Smooth polished finish with subtle shine',
      tag: 'daily',
      sizes: ['Small', 'Medium', 'Large'],
    },
  ],
  Anklets: [
    {
      name: 'Diamond Anklet',
      collection: 'Footnotes',
      price: 21400,
      compareAtPrice: 24900,
      image: '/Diamond Anklet.jpg',
      alt: 'Diamond anklet by Shree Yash Diamond and Jewels',
      description: 'A refined anklet designed to add a soft shimmer to festive and evening styling.',
      material: 'Gold vermeil with diamonds',
      diamondDetails: 'Delicate sparkle detailing with smooth clasp',
      tag: 'diamond',
      sizes: ['Adjustable'],
      featured: true,
    },
    {
      name: 'Pearl Anklet',
      collection: 'Soft Shore',
      price: 19200,
      compareAtPrice: 22900,
      image: '/Pearl Anklet.webp',
      alt: 'Pearl anklet by Shree Yash Diamond and Jewels',
      description: 'A feminine pearl anklet with a refined finish for easy festive layering.',
      material: 'Gold vermeil with cultured pearls',
      diamondDetails: 'Graceful pearl line with delicate sparkle',
      tag: 'pearl',
      sizes: ['Adjustable'],
    },
    {
      name: 'Gold Anklet',
      collection: 'Velvet Light',
      price: 17600,
      compareAtPrice: 20900,
      image: '/Gold Anklet.jpg',
      alt: 'Gold anklet by Shree Yash Diamond and Jewels',
      description: 'A minimal anklet made for everyday elegance with subtle warmth and polish.',
      material: 'Gold vermeil',
      diamondDetails: 'Clean profile and adjustable fit',
      tag: 'gold',
      sizes: ['Adjustable'],
    },
  ],
  Chains: [
    {
      name: 'Delicate Gold Chain',
      collection: 'Minimal Glow',
      price: 21400,
      compareAtPrice: 24900,
      image: '/Delicate Gold Chain.webp',
      alt: 'Delicate gold chain by Shree Yash Diamond and Jewels',
      description: 'An everyday chain with a refined air of elegance that layers effortlessly with pendants.',
      material: 'Gold vermeil',
      diamondDetails: 'Fine link structure with smooth polish',
      tag: 'chain',
      sizes: ['16 inch', '18 inch', '20 inch'],
      bestseller: true,
    },
    {
      name: 'Statement Chain',
      collection: 'Bold Moderne',
      price: 26800,
      compareAtPrice: 30900,
      image: '/Statement Chain.avif',
      alt: 'Statement chain by Shree Yash Diamond and Jewels',
      description: 'A bolder chain profile designed for elevated festive dressing and layered styling.',
      material: '18K gold vermeil',
      diamondDetails: 'Chunky link design with polished finish',
      tag: 'statement',
      sizes: ['18 inch', '20 inch'],
    },
    {
      name: 'Layered Chain Set',
      collection: 'Stacked Luxe',
      price: 29600,
      compareAtPrice: 34100,
      image: '/Layered Chain Set.avif',
      alt: 'Layered chain set by Shree Yash Diamond and Jewels',
      description: 'A graceful layered chain set crafted for soft drama and polished modern styling.',
      material: 'Gold vermeil',
      diamondDetails: 'Multi-length coordinate chain finish',
      tag: 'layered',
      sizes: ['16 inch', '18 inch'],
      newArrival: true,
    },
  ],
  'Bridal Earring': [
    {
      name: 'Bridal Jhumka Earrings',
      collection: 'Shaadi Glow',
      price: 35600,
      compareAtPrice: 40900,
      image: '/be 1.jpg',
      alt: 'Bridal jhumka earrings by Shree Yash Diamond and Jewels',
      description: 'Traditional jhumka styling elevated with premium sparkle for bridal celebrations.',
      material: 'Gold vermeil and diamond accents',
      diamondDetails: 'Intricate bridal bead and diamond detailing',
      tag: 'bridal-earring',
      sizes: ['One size'],
      featured: true,
    },
    {
      name: 'Bridal Chandbali',
      collection: 'Royal Wedding',
      price: 38900,
      compareAtPrice: 44900,
      image: '/be 2.jpg',
      alt: 'Bridal chandbali earrings by Shree Yash Diamond and Jewels',
      description: 'A regal chandbali design with a refined finish suited for festive bridal styling.',
      material: 'Gold vermeil with precious stones',
      diamondDetails: 'Traditional crescent silhouette with sparkle edge',
      tag: 'bridal',
      sizes: ['One size'],
    },
    {
      name: 'Pearl Bridal Earrings',
      collection: 'Wedding Aura',
      price: 34200,
      compareAtPrice: 39800,
      image: '/be 3.webp',
      alt: 'Pearl bridal earrings by Shree Yash Diamond and Jewels',
      description: 'Pearl bridal earrings designed to frame a soft, elegant wedding look with luxe polish.',
      material: 'Gold vermeil and pearls',
      diamondDetails: 'Pearl drop finish with luxurious edge detailing',
      tag: 'bridal-pearl',
      sizes: ['One size'],
    },
  ],
  'Bridal Bangles': [
    {
      name: 'Bridal Kangan Set',
      collection: 'Wedding Story',
      price: 47600,
      compareAtPrice: 54900,
      image: '/Bridal Kangan Set.jpg',
      alt: 'Bridal kangan set by Shree Yash Diamond and Jewels',
      description: 'A regal bridal bangle set made for festive, heirloom-inspired wedding styling.',
      material: 'Gold vermeil with diamond accents',
      diamondDetails: 'Polished kangan silhouette with bridal sparkle',
      tag: 'kangan',
      sizes: ['Medium', 'Large'],
      featured: true,
    },
    {
      name: 'Bridal Kada',
      collection: 'Royal Grace',
      price: 42900,
      compareAtPrice: 49500,
      image: '/Bridal Kada.webp',
      alt: 'Bridal kada by Shree Yash Diamond and Jewels',
      description: 'A statement bridal kada with a graceful balance of traditional appeal and soft sparkle.',
      material: 'Gold vermeil with stone accents',
      diamondDetails: 'Heirloom-inspired kada with fine cuts',
      tag: 'bridal',
      sizes: ['Medium', 'Large'],
      bestseller: true,
    },
    {
      name: 'Bridal Bangle Stack',
      collection: 'Heritage Shine',
      price: 45600,
      compareAtPrice: 52100,
      image: '/Bridal Bangle Stack.webp',
      alt: 'Bridal bangle stack by Shree Yash Diamond and Jewels',
      description: 'A bridal stack designed to create layered elegance with a rich, ceremonial finish.',
      material: 'Gold vermeil and diamonds',
      diamondDetails: 'Layered bangle design with luminous stones',
      tag: 'bridal-bangle',
      sizes: ['Medium', 'Large'],
    },
  ],
  'Bridal Necklace': [
    {
      name: 'Bridal Choker Set',
      collection: 'Forever Bridal',
      price: 52800,
      compareAtPrice: 60900,
      image: '/Bridal Choker Set.jpg',
      alt: 'Bridal choker set by Shree Yash Diamond and Jewels',
      description: 'A statement choker set crafted to frame the neckline with luxe bridal detailing.',
      material: 'Gold vermeil with stones',
      diamondDetails: 'Statement collar silhouette with brilliant stone work',
      tag: 'bridal-necklace',
      sizes: ['Custom fit'],
      featured: true,
    },
    {
      name: 'Pearl Bridal Necklace',
      collection: 'Wedding Light',
      price: 46200,
      compareAtPrice: 52800,
      image: '/Pearl Bridal Necklace.avif',
      alt: 'Pearl bridal necklace by Shree Yash Diamond and Jewels',
      description: 'A soft pearl bridal necklace shaped for graceful, luminous reception styling.',
      material: 'Gold vermeil with cultured pearls',
      diamondDetails: 'Pearl strands with polished setting accents',
      tag: 'pearl',
      sizes: ['Custom fit'],
    },
    {
      name: 'Bridal Pendant Necklace',
      collection: 'Heirloom Glow',
      price: 49500,
      compareAtPrice: 56900,
      image: '/Bridal Pendant Necklace.jpg',
      alt: 'Bridal pendant necklace by Shree Yash Diamond and Jewels',
      description: 'An elegant bridal pendant necklace crafted to sit beautifully with wedding couture.',
      material: 'Gold vermeil with diamonds',
      diamondDetails: 'Smooth pendant finish with luminous stone accents',
      tag: 'bridal',
      sizes: ['Custom fit'],
      bestseller: true,
    },
  ],
  'Bridal Other Jewelleries': [
    {
      name: 'Bridal Maang Tikka',
      collection: 'Wedding Aura',
      price: 22500,
      compareAtPrice: 26400,
      image: '/Bridal Maang Tikka.webp',
      alt: 'Bridal maang tikka by Shree Yash Diamond and Jewels',
      description: 'An opulent maang tikka designed to bring a regal bridal finish to the forehead styling.',
      material: 'Gold vermeil with stones',
      diamondDetails: 'Decorative pendant and embellished frame',
      tag: 'bridal-accessory',
      sizes: ['Adjustable'],
    },
    {
      name: 'Bridal Nath',
      collection: 'Royal Touch',
      price: 19800,
      compareAtPrice: 23900,
      image: '/Bridal Nath.jpg',
      alt: 'Bridal nath by Shree Yash Diamond and Jewels',
      description: 'A statement bridal nath designed to add a radiant, traditional finishing touch.',
      material: 'Gold vermeil with pearls and stones',
      diamondDetails: 'Ornamental bridal nose style with polished accents',
      tag: 'bridal',
      sizes: ['One size'],
    },
    {
      name: 'Bridal Toe Rings',
      collection: 'Blessed Beginnings',
      price: 13800,
      compareAtPrice: 16900,
      image: '/bridal toe ring.jpg',
      alt: 'Bridal toe rings by Shree Yash Diamond and Jewels',
      description: 'A delicate bridal toe ring set created for wedding ritual styling with a polished finish.',
      material: 'Gold vermeil',
      diamondDetails: 'Softly polished design with festive detailing',
      tag: 'bridal',
      sizes: ['Adjustable'],
    },
  ],
}

const additionalCategoryProducts: Product[] = Object.entries(categoryProductCatalog).flatMap(([category, entries]) =>
  entries.map((entry, index) => ({
    id: `${category.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${entry.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${index + 1}`,
    name: entry.name,
    category,
    collection: entry.collection,
    price: entry.price,
    compareAtPrice: entry.compareAtPrice,
    image: entry.image,
    alt: entry.alt,
    description: entry.description,
    material: entry.material,
    diamondDetails: entry.diamondDetails,
    tag: entry.tag,
    sizes: entry.sizes,
    featured: entry.featured,
    bestseller: entry.bestseller,
    newArrival: entry.newArrival,
  })),
)

export const products: Product[] = [...existingProducts, ...additionalCategoryProducts]

export const testimonials = [
  { id: 1, customerName: 'Riya S.', location: 'Mumbai', product: 'Celeste Diamond Ring', review: 'The design feels effortlessly premium and delicate. It arrived beautifully presented and exceeded my expectations.', rating: 5 },
  { id: 2, customerName: 'Aarti M.', location: 'Delhi', product: 'Ira Halo Necklace', review: 'The craftsmanship is elegant and true to the premium style I wanted for a family celebration.', rating: 5 },
  { id: 3, customerName: 'Pooja K.', location: 'Jaipur', product: 'Meher Pearl Drop Earrings', review: 'The finish is refined and the quality feels exceptional. A perfect gift for a special occasion.', rating: 4 },
]

export const faqs = [
  { question: 'How can I place an order?', answer: 'Browse collections, select your preferred piece, add it to cart, and continue with the checkout form. Our team will confirm the order details shortly after placement.' },
  { question: 'Do you offer custom jewellery?', answer: 'Yes. Our custom jewellery consultation is available for bespoke pieces and personalised design requests. Please use the consultation form or contact us directly.' },
  { question: 'Are the diamonds certified?', answer: 'Certification details can be shared at the time of purchase for specific pieces. Please mention your requirement in the consultation form or order enquiry.' },
  { question: 'Do you offer shipping across India?', answer: 'Yes, pan-India shipping is available and can be confirmed on the order and delivery section at checkout.' },
  { question: 'What is your return/exchange policy?', answer: 'Return and exchange terms are managed by the brand team and can be updated in the admin settings as policies are finalised.' },
  { question: 'How can I book a jewellery consultation?', answer: 'Use the consultation form in the custom jewellery section or contact the team by phone or email for a personalised browsing appointment.' },
  { question: 'How can I contact customer support?', answer: 'You can reach our team through the contact page, WhatsApp, email, or the phone number available in the footer and header.' },
]

export const trustFeatures = [
  { title: 'Certified Jewellery', description: 'Curated designs with quality checks for bespoke selection and trusted presentation.' },
  { title: 'Personalised Consultation', description: 'A dedicated team to assist with gifting, bridal styling and bespoke discovery.' },
  { title: 'Secure Packaging', description: 'Elegant, protective delivery for keepsakes and occasion gifting.' },
  { title: 'Pan-India Delivery', description: 'Reliable shipping support across India for gifting and bridal orders.' },
]

export const socialImages = [
  '/fts1.jpg',
  '/fts%203.jpg',
  '/fts2.jpg',
]

export const navItems = ['Home', 'Shop', 'About Us', 'Contact']

export const festiveGifts = [
  { title: 'Birthday', image: '/birthday.jpg' },
  { title: 'Engagement', image: '/engaement.webp' },
  { title: 'Wedding', image: '/wedding.jpg' },
  { title: 'Anniversary', image: '/anniversary.webp' },
  { title: 'Festive Gifting', image: '/festive.webp' },
]

export const diamondsFeatures = [
  { title: 'Exceptional Craftsmanship', icon: '✦', description: 'Thoughtful detailing and refined finishing in every bespoke design.' },
  { title: 'Certified Diamonds', icon: '◌', description: 'Diamond choices are curated with quality and clarity in mind for each piece.' },
  { title: 'Timeless Designs', icon: '❋', description: 'Minimal silhouettes built to remain meaningful across seasons and milestones.' },
  { title: 'Personalised Service', icon: '✧', description: 'A consultation-led approach to gifting, bridal styling, and tailored jewellery.' },
]
